### ISSUE TITLE
想问下为什么采用这种归一化方式，与原文中不一致

### ISSUE THREAD

**Issue by liu-hx** [YOUSIKI/PyTorch-FBS#2]
https://github.com/YOUSIKI/PyTorch-FBS/blob/5e94c3183f064ef5ed7f4b7d82b076056200b368/models/custom.py#L70

如题

**Comment by yousiki** [comment]
我记得当时是因为，如果不这样，很容易炸到 INF，不确定是正确的。顺便一提我早已经离开这个领域了。所以，您自己加油💪🏻

**Comment by liu-hx** [comment]
好的，非常感谢您的回复
